"""Type stubs for the ``pyenum_test`` cdylib fixture.

Kept in sync with ``crates/pyenum-test/src/lib.rs``. Updating the Rust
side requires matching edits here — there is no automatic stub generator
for enums built through the functional ``enum.Enum("Name", members)``
API.
"""

from __future__ import annotations

import enum

# ---------------------------------------------------------------------------
# Fixture enums — one per supported Python base.
# ---------------------------------------------------------------------------

class Color(enum.Enum):
    Red = ...
    Green = ...
    Blue = ...

class HttpStatus(enum.IntEnum):
    Ok = ...
    NotFound = ...
    Teapot = ...

class Greeting(enum.StrEnum):
    Hello = ...
    World = ...
    Bye = ...

class Language(enum.StrEnum):
    """Variant values are explicit strings via ``#[pyenum(value = "...")]``."""

    Rust = ...
    Python = ...
    TypeScript = ...

class Permission(enum.Flag):
    Read = ...
    Write = ...
    Execute = ...

class BitPerms(enum.IntFlag):
    Read = ...
    Write = ...
    Execute = ...
    Admin = ...

class UnpicklableColor(enum.Enum):
    Red = ...
    Green = ...
    Blue = ...

# ---------------------------------------------------------------------------
# Round-trip helpers — each takes and returns the matching enum type,
# exercising the ``FromPyObject`` + ``IntoPyObject`` codegen paths.
# ---------------------------------------------------------------------------

def color_roundtrip(c: Color) -> Color: ...
def http_roundtrip(s: HttpStatus) -> HttpStatus: ...
def greeting_roundtrip(g: Greeting) -> Greeting: ...
def language_roundtrip(l: Language) -> Language: ...
def permission_roundtrip(p: Permission) -> Permission: ...
def bitperms_roundtrip(p: BitPerms) -> BitPerms: ...

# ---------------------------------------------------------------------------
# Test-only introspection — returns the number of times the cached Python
# class for a registered Rust enum type has been built. Raises ``TypeError``
# for classes not produced by this fixture.
# ---------------------------------------------------------------------------

def _construction_count(cls: type[enum.Enum]) -> int: ...
